--Disparador 1

--Código

CREATE OR REPLACE TRIGGER EMPLEADOS_AI 
    AFTER INSERT ON HIJOS 
    FOR EACH ROW
BEGIN
    UPDATE EMPLEADOS SET NUMHIJ_EM = NUMHIJ_EM + 1 WHERE COD_EM = :NEW.PADRE_HI;
END EMPLEADOS_AI;
/

--Consulta del Número de Hijos del Empleado

SELECT NUMHIJ_EM FROM EMPLEADOS WHERE COD_EM = 1;

--Inserción de un Nuevo Hijo para el Empleado

INSERT INTO HIJOS VALUES (1, 3, '12/06/2022', 'Ruiz Del Junco, Roberto');

--Consulta del Número de Hijos Actualizado del Empleado

SELECT NUMHIJ_EM FROM EMPLEADOS WHERE COD_EM = 1;

--Disparador 2

--Creación de Tabla REG_EMPLEADOS

CREATE TABLE REG_EMPLEADOS
(
    COD_EM NUMBER(6),
    FECREG VARCHAR2(50)
);

--Código

CREATE OR REPLACE TRIGGER EMPLEADOS_BIUD
    BEFORE INSERT OR UPDATE OR DELETE ON EMPLEADOS
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO REG_EMPLEADOS VALUES (:NEW.COD_EM, 'FECHA DE REGISTRO DE NUEVO EMPLEADO: ' || SYSDATE);
    ELSIF UPDATING THEN 
        INSERT INTO REG_EMPLEADOS VALUES (:OLD.COD_EM, 'FECHA DE MODIFICACIÓN DE EMPLEADO: ' || SYSDATE);
    ELSIF DELETING THEN 
        INSERT INTO REG_EMPLEADOS VALUES (:OLD.COD_EM, 'FECHA DE BORRADO DE EMPLEADO: ' || SYSDATE);
    END IF;    
END EMPLEADOS_BIUD;
/

--Inserción de un Nuevo Empleado 

INSERT INTO EMPLEADOS VALUES (90, 300, 2233, SYSDATE, '23/07/1965', '53617687K', 'Valverde Gallego, Enrique', 0, 4500000, null);

--Actualización del Empleado 

UPDATE EMPLEADOS SET SALARIO_EM = 5000000 WHERE COD_EM = 90;

--Borrado del Empleado

DELETE EMPLEADOS WHERE COD_EM = 90;

--Visualización de las Entradas Generadas en la Tabla REG_EMPLEADOS

SELECT * FROM REG_EMPLEADOS;
